### ISSUE TITLE
`UserId` doesn't parse the user ID from the IRC bridge

### ISSUE THREAD

**Issue by aledomu** [ruma/ruma-identifiers#11]
I'm using this crate in Fractal to have proper types with format validation. When trying to parse a user ID like `@freenode_tigran[m]:matrix.org` it returns an `Error`. More details [here](https://gitlab.gnome.org/GNOME/fractal/issues/554).

**Comment by florianjacob** [comment]
This is only valid as a [historical user id](https://matrix.org/docs/spec/appendices#historical-user-ids), but not as normal [user id](https://matrix.org/docs/spec/appendices#user-identifiers).

Ruma currently does enforce normal user ids.
We have to support historic user ids from other sources though:

> clients and servers MUST accept user IDs with localparts from the expanded character set:
> all ascii printing chars except :

While the freenode bridge really should not create historical user ids and should escape `[` etc somehow (@aledomu maybe you could open a bug for that as well?), and ruma can still disallow usage and creation of historic user ids via the client, it needs to accept historic user ids by the current spec. I think it could work out to have two ways of constructing a UserID, one only used for deserialization of received events which uses the expanded character set, and the other one for everything else.

**Comment by jplatte** [comment]
Didn't know that 'historic' user ids were part of the spec now. I think we could make UserId into an enum of NormalUserId, HistoricUserId, with string conversion, localpart extraction etc on the enum as well as the individual types. (this time it can for sure be an exhaustive enum)

Does one of you want to take on implementation of this?

**Comment by aledomu** [comment]
I'll take it.

**Comment by florianjacob** [comment]
Having those methods on the enum could even make this change mostly transparent to the user, and also if someday historic user IDs are really a thing of the past, the enum can be replaced again. Good idea! :+1:

**Comment by jplatte** [comment]
@aledomu ping. Do you still plan to work on this?

**Comment by aledomu** [comment]
Life got busy lately and I won't be able to start this until Christmas, so if any of you can do it I'll appreciate it.

**Comment by jplatte** [comment]
I've started working on this.

**Comment by jplatte** [comment]
Fixed in https://github.com/ruma/ruma-identifiers/commit/d19d9c054feb7e83993c25f399c256ba520e5142

Will be released as part of ruma-identifiers 0.14.1 soon.

**Comment by jplatte** [comment]
ruma-identifiers 0.14.1 has been released.
