### ISSUE TITLE
Make user identifiers case sensitive

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-identifiers#12]
Because user identifiers weren't always as strict on matrix.org (and the spec?) as they are in the spec now, some people have user identifiers with non-lowercase letters. We shouldn't lowercase them and instead mark them as legacy user ids.

**Comment by MTRNord** [comment]
The chapter how to handle these old MXIDs is here: https://matrix.org/docs/spec/appendices#historical-user-ids

My MXID is affected by this "bug": @MTRNord:matrix.ffslfl.net (Not the upper case characters of the ID. This is NOT the same user as @mtrnord:matrix.ffslfl.net )
