### ISSUE TITLE
EventId type is not compatible with v3 Rooms

### ISSUE THREAD

**Issue by encombhat** [ruma/ruma-identifiers#9]
In v3 rooms, event id looks like `$qfx9N7OyzsdJkP8QNy302f6Na1a65DxfioiGYzlTYPs`.
As a result, ruma-identifier cannot parse it.

**Comment by aaronraimist** [comment]
Looks like https://github.com/ruma/ruma-identifiers/releases/tag/0.13.0 fixes this?
